### ISSUE TITLE
BYUi Assignments Posted Publicly

### ISSUE THREAD

**Issue by danielwells** [brycematheson/javascript-basics#1]
Bryce, would you mind deleting your CIT 160 from GitHub (or move it to a private repo)?  I have had several students submitting your code as their own.  While this is not your fault, removing the temptation might beneficial.

**Comment by brycematheson** [comment]
Brother Wells,

While I understand that your students are copying my work, I respectfully decline to remove it from GitHub.

As you know, GitHub is an open-sourced community which allows users to share code and other content. I feel that this code is beneficial to not only myself, but others as well, and will leave it open to the public. 

Rather than simply “removing the temptation” for your students, I would hope that you would instill an environment of honesty and integrity in your classroom, as an alternative.

Thank you
-Bryce

**Comment by danielwells** [comment]
Bryce,

Thank you for your response.  I am a huge supporter of the ideas behind open source and the benefits of shared code.  However I believe that using that justification is perhaps over simplifying this situation.  Having attended BYUI I am sure that you understand the as instructors, we try very hard to model the values of the University and encourage those values from our students.  But ultimately it is the student’s responsibility to live by them.  Let me present an alternate viewpoint and some additional ideas for you to ponder.

I would assume that you would agree with me that it would be inappropriate for an on-campus student to complete some individual coursework, or exam, in class and then proceed to post his answers outside the classroom for all to see.  I don’t think anyone would question the instructor who chooses to take those down.  Now, let’s assume that same student takes those answers home and shares them with a roommate who has the same class at a later date in the week.  According to how the University defines cheating, both students (the one that shared and the one that took) would be held culpable in this situation and action could be taken on both.  Here are two bullet points from the University’s definition of cheating

•	Allowing someone to copy work that is not his or her own during an examination or while completing an assignment
•	Collaborating on an examination or assignment without authorization

I thoroughly believe that your reasons for posting this code are noble.  But please consider the fact that sharing this code online is really no different than the scenarios I have shared above.  In fact, it has wider implications.  Maybe the intent is different.  But by definition, it is still the first half of the cheating equation. 

I ask you to please reconsider your position.
